MODULE FormsDriverExt;

REQUIRE   CalcTask,Utils;

NAMESPACE Forms;

openTask(Calc c, Task cc)+{
         checkOrCreateCalcTask(c,cc);
          NEWSESSION {
           // regexpReplace - убираем namespace с точкой слева
           IF type(cc) THEN
            EVAL ACTION  'SHOW  form' + regexpReplace(staticName(type(cc)),'.*[.]','','')+ ' OBJECTS calcTask = getCalcTask($1,$2) DOCKED NOWAIT MANAGESESSION ' PARAMS  c, cc ;
        }
}  
 